spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/smartops
spring.datasource.username=root
spring.datasource.password=Shendkar@921

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ThisIsMyVerySecretKeyForSmartOpsProject123456
app.jwt.expiration=86400000